name: Label Notification

on:
  issues:
    types: [labeled]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Trim issue body to 3 lines
      id: trim_body
      run: |
        echo "${{ github.event.issue.body }}" | head -n 3 > trimmed_body.txt
        echo "TRIMMED_BODY<<EOF" >> $GITHUB_ENV
        while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done < trimmed_body.txt
        echo "EOF" >> $GITHUB_ENV

    - name: Send Discord Notification
      if: contains(github.event.issue.labels.*.name, 'ko-locale')
      env:
        TRIMMED_BODY: ${{ env.TRIMMED_BODY }}
      run: |
        echo "'"${TRIMMED_BODY}"'"
