name: Label Notification

on:
  issues:
    types: [labeled]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Trim issue body to 3 lines
      id: trim_body
      run: |
        echo "${{ github.event.issue.body }}" | head -n 3 > trimmed_body.txt
        echo "TRIMMED_BODY<<EOF" >> $GITHUB_ENV
        while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done < trimmed_body.txt
        echo "EOF" >> $GITHUB_ENV
    - name: Send Email Notification
      if: contains(github.event.issue.labels.*.name, 'l10n-ko')
      env:
        TRIMMED_BODY: ${{ env.TRIMMED_BODY }}
      run: |
        trimmed_body=$(cat trimmed_body.txt)
        echo -e "Subject: KO ISSUE NOTIFICATION: ${{ github.event.issue.title }}\nTo: yari-content-ko@googlegroups.com\nContent-Type: text/plain; charset=UTF-8\n\nIssue URL: ${{ github.event.issue.html_url }}\n\nDescription:\n$trimmed_body" > email.txt
        sendmail hochan049@gmail.com < email.txt
